all:
  hosts:
    homeassistant:
      ansible_host: ha.mpagel.de
      ansible_user: root
      ansible_port: 22
      homeassistant_config_path: /config
      pyscript_path: /config/pyscript
      addon_configs_path: /addon_configs
