secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: 48.123397
  longitude: 11.158601
  elevation: 543
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
      token: !env_var SUPERVISOR_TOKEN
    MQTT:
      # prefix of plugin module:
      type: mqtt
      # "default" is used by HASS plugin, so use a different one:
      namespace: mqtt
      client_host: core-mosquitto
      client_user: ha-mqtt
      client_password: !secret ha_mqtt_password
      # let apps decide which topics to listen to:
      client_topics: [None]
  # all applications use a pure asynchronous model, no threads required:
  total_threads: 0
  use_dictionary_unpacking: true
# HTTP endpoint exposed by AppDaemon:
http:
  url: http://0.0.0.0:5050
  ssl_certificate: /ssl/nginxproxymanager/live/npm-3/fullchain.pem
  ssl_key: /ssl/nginxproxymanager/live/npm-3/privkey.pem
  password: !secret appdaemon_password
admin:
# api:
# hadashboard:
