- name: Deploy custom AppDaemon applications to Home Assistant
  hosts: all
  gather_facts: false

  roles:
    - role: homeassistant
      tags: homeassistant
    - role: appdaemon
      tags: appdaemon
