- name: Deploy Home Assistant applications and configurations
  hosts: all
  gather_facts: false

  roles:
    - role: homeassistant
      tags: homeassistant
    - role: pyscript
      tags: pyscript
